version: '3.9'

services:

# ---------------------------------
# laravelを動かすコンテナ
# ---------------------------------
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    # ports:
    #   - 80:80
    container_name: laravel_app
    links:
      - db
    volumes:
      - ./src/:/var/www/html

# ---------------------------------
# MySQLを動かすコンテナ
# ---------------------------------
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: laravel_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root@localhost
      MYSQL_PASSWORD: yaku
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d

# ---------------------------------
# nginxを動かすコンテナ
# ---------------------------------
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./src/:/app
